### PR TITLE
Festival day enum

### LINKED ISSUE #18: FestivalDay enum
enum needs to be refactored

### PR DESCRIPTION
**Pull request by NVI**
fixes #18

### CODE REVIEW

**Comment by pahuttun** [comment]
This pull request is almost accepted. Please do following fixes:
- Instead of this.getBaseContext() you could only use: this

You can fix this following way:
- Do fix stated above
- Test
- Commit and push -> pull request will change
- Leave comment on pull request that you have done fixes

**Comment by pahuttun** [comment]
Forgot one thing!
- Missing also finnish translation (check: res/values-fi -folder)

**Comment by NVI** [comment]
Changes made accordingly.

**Comment by pahuttun** [comment]
Good job!

Pull request will be now merged.

**Pull request merged**
