### PR TITLE
Make map and clickable map areas more configurable

### PR DESCRIPTION
**Pull request by pahuttun**
Changes:
- Make map and clickable map areas more configurable
- Replace old map with temporary test map with clickable areas (which will work when gig data is returned from backend)

### CODE REVIEW

**Comment by pahuttun** [comment]
Solves issue #32 
Solves issue #33

**Comment by phadej** [comment]
Is there an issue to makes the clickable areas configurable thru data file.

**Comment by pahuttun** [comment]
Not yet. Mainly because both clickable areas and stages were hardcoded in code and only reason to click map was to get info from artists on clicked stage. There would be no reason to make clickable areas fully configurable thru data files if stages are not configurable also. Creating stages configurable will be quite a big job, but of course it would be good thing to do.

I'll create issue to make both configurable thru datafiles.

**Comment by wijnbladh** [comment]
Looks solid, tested map touching by giving the toast an arbitrary message. Worked nicely, approved.

**Pull request merged**
