### PR TITLE
Fixes to date handling

### PR DESCRIPTION
**Pull request by kazenokage**
Please review before merging - some of the stuff overlaps with other teams' code, and may not be necessary.

### CODE REVIEW

**Comment by joelmertanen** [comment]
please merge to current master and test

**Comment by Tsarpf** [comment]
@joelmertanen Merged but broken, because some other team is doing something with the database's tables which breaks our stuff too.

**Comment by Tsarpf** [comment]
Actually no errors when we refreshed our local databases. Just no days show up on the schedule,

**Comment by Tsarpf** [comment]
Now days show up too even though we didn't change anything

**Comment by Tsarpf** [comment]
Ready for merge methinks

**Comment by NVI** [comment]
I believe there would be better ways to edit out git merge errors than commenting them in the code. Also, judging from the diff there seem to be some non-UTF-8 characters.

**Comment by Tsarpf** [comment]
Oh yeah we forgot some there since we weren't 100% sure which one to choose. Also FYI if you didn't notice there were 10x the amount of merge errors fixed than the amount of commented out ones. Trying to do something about the stuff you mentioned now.

**Comment by Tsarpf** [comment]
@NVI I think I removed what you mentioned. Couldn't find non-UTF8 stuff. Please either point out where they are or fix them yourselves when you can.

**Comment by NVI** [comment]
They should be present in the "Files changed" view in this very web interface.

**Comment by Tsarpf** [comment]
@NVI So you are saying changes can be seen from where the changes are? Helpful...

 Since you bothered to respond you might as well had pointed out the exact locations with minimal added effort compared to just responding and saved everyone's time. 

Anyway thanks and fix'd

**Comment by NVI** [comment]
Well I thought they were really easily spottable from that view. All are in the file res/raw/gigs.json and it seems that they're still there.

**Comment by Tsarpf** [comment]
They're just test data. They'll always be replaced by actual data.

**Pull request closed without merging**
