### PR TITLE
Issue52

### PR DESCRIPTION
**Pull request by sorja**
Fixed some minor things

### CODE REVIEW

**Comment by joelmertanen** [comment]
has some typos in eg. db init, requires testing.

**Comment by ktuukkan** [comment]
Does not compile, please check StageDAO.

**Comment by WaDelma** [comment]
Hmm... There is no StageDAO in this...

**Comment by WaDelma** [comment]
There. The branch was bit out of date with master...

**Comment by ktuukkan** [comment]
Still some problems, tapping Schedule or Bands on main menu makes the app crashing. Seems like missing a column in db (no such column: gig.artistimage).

**Pull request merged**
