### PR TITLE
replacements and generalizations for dates

### LINKED ISSUE #86: Event is always ended, none of the HTTP GETs are actually run!
In main activity and fest app service, the following test is ATM always false:

```
    if (nowDate.before(GigDAO.getEndOfSunday())) {
```

It masks a great deal of issues because the content is never actually updated.

### PR DESCRIPTION
**Pull request by NVI**
fixes #86

### CODE REVIEW

**Comment by joelmertanen** [comment]
please merge to current master and test

**Comment by NVI** [comment]
Merged and tested to work.

**Comment by joelmertanen** [comment]
waits for small stylish fixes

**Comment by NVI** [comment]
Commit has been amended to incorporate style improvements.

**Comment by joelmertanen** [comment]
This exposes lots of bugs, awesome! I'll create another ticket for the user to be able to configure the length of the festival.

**Pull request merged**
