### PR TITLE
Fixes issue #50

### PR DESCRIPTION
**Pull request by ljleppan**
A checkbox in Debug-menu for ignoring ETags when deciding whether to get new data from backend and a button for forcing the retrieval of data.

Due to backend changes, no testing with real backend data was possible.

### CODE REVIEW

**Comment by wijnbladh** [comment]
Heyas, I recommend we don't merge this yet. See the following comments:
- Change the location of F_IGNORE_ETAG, perhaps F_DEBUG too. A better home might be the file FestAppContants.java at least for now, although I think there is an issue open about moving those constants somewhere else as well. This way FestAppService and HTTPUtil don't need to know about DebugActivity.
- The "Clear DB" button could be hidden for now, since it is not functional
- FestAppService should probably only rely on the Intent, and not access DebugActivity directly. This might remove the concurrency problem as well, when DebugActivity becomes the only setter of F_IGNORE_ETAG, FestAppService (along with HTTPUtil) only reads it.
- There is a bit of unclarity in the implementation currently. If I got this right, clicking the "Fetch all data from server" button will set F_IGNORE_ETAG to true for a moment, then runs backendTask.run() in FestAppService, then sets F_IGNORE_ETAG back to what it was. However, the fetch is still constrained by the counter -variable in FestAppService. Maybe change it so that clicking the button only runs the backendTask in a way that the counter-variable is skipped (i.e. "fetch all data"). Then, on top of that, if the F_IGNORE_ETAG, it should fetch "all data regardless of the ETag". 
- Also, maybe change it so that F_IGNORE_ETAG can be controlled with the checkbox only (i.e. FestAppService should not change it), and reference F_IGNORE_ETAG in this line rather than constant "true":
  
  (DebugActivity, line 27): i.putExtra("com.futurice.festapp.service.FORCE", true);

**Comment by dwmh** [comment]
The suggestions above have been made with one exception: the checkbox for ignoring has been completely removed and the forced reload of data is just done with the button now. This approach is much simpler and the checkbox toggling did not really bring much value for debugging.

**Comment by wijnbladh** [comment]
Ok, just a few more things:
- The Debug UI got a bit messed up, the button is now partially over the view header
- In FestAppService, if flag F_IGNORE_ETAG is on, it will do the forced fetch and immediately after it will do the usual fetch. Maybe add an else-statement around line 52 in FestAppService.java.
- Maybe rename F_IGNORE_ETAG into F_FORCE_DATA_FETCH, or so.

Btw. there is something else wrong under the hood, each time the FestAppService is invoked, it is actually invoked twice, other invocation comes from ServiceBroadcastReceiver.java. Looks like this is already present in the original version, so it does not necessarily concern this pull request. You may want to take a look tho, just watch the logcat when you invoke FestAppService, it will print stuffs like "Running cron tasks", etc., twice.

**Comment by dwmh** [comment]
Fixes have been made. I will create a new issue from the duplicated data requests problem.

**Comment by wijnbladh** [comment]
Nice work, let's go with this. Thanks!

**Pull request merged**
